- src/Migration/Migration.php
- src/View/Migration.php
> add import sender mail/name and codes

- src/Repository/BookingCodes.php
- src/Repository/CB1.php
- src/Repository/Timeframe.php
@markus-mw : Bitte nochmal prüfen, ob das so korrekt ist. Du kennst deine Master-Queries ja wat besser..
> bugfix/issue-404: added missing table prefixes

- src/Wordpress/CustomPostType/Timeframe.php
- templates/timeframe-notallowed.php
> added condition to prevent preview of non-booking timeframes in frontend

- src/Wordpress/CustomPostType/Location.php
> Station erstellen: Textanpassungen

- src/Wordpress/CustomPostType/Timeframe.php
This is not exactly the refactoring mentioned in #532 but should do the trick.
> Prevent mail if unconfirmed booking gets canceled

- templates/dashboard-index.php
> Added Maps to dashboard

- assets/map/js/cb-map-filters.js
- templates/map-admin-page-template.php
@markus-mw kannst du das bitte mal checken, ob das so passt? Geht darum, den Min-Wert auf 1 zu setzen in dem Map-Filter.
siehe #549
> fix missing default value day_count in map availability filter #549

- src/Repository/Booking.php
- src/View/Item.php
- src/View/Location.php
- tests/Repository/BookingTest.php
- tests/Wordpress/CustomPostTypeTest.php
Ich würde es begrüßen, wenn wir eine möglichst hohe Testabdeckung für zumindest die Repos erreichen würden. Einiges ist schon getan, aber es bleibt Luft nach oben.
Schaut euch das bitte mal an und lasst uns mal einen Termin machen, in dem wir das bei euch einrichten, falls ihr das nicht schon haben solltet.
> added full set of tests for booking repository

- src/View/Location.php
> locationview map fixes issue #916

- src/Plugin.php
> added function to set advance booking days default value on update fixes

- templates/booking-single.php
- templates/item-calendar-header.php
- templates/item-single.php
- templates/location-calendar-header.php
- templates/location-single.php
- templates/timeframe-calendar.php
> added action hooks #947

- src/Plugin.php
> changes hook to fire after postmeta update fixes #952

- assets/admin/sass/admin.scss
- src/Plugin.php
> Add CSS class 'cb-admin' to body of admin pages

- includes/TemplateParser.php
- src/CB/CB.php
- src/Messages/Message.php
- src/View/Booking.php
- src/Wordpress/CustomPostType/Map.php
> unifies filter hook names

- src/Model/CustomPost.php
Kann man das so machen? Ich meine es funktioniert, aber ich bin mir unsicher ob das so clean ist.
> do not return property when no post present fixes #675

- src/Wordpress/CustomPostType/Booking.php
- src/Wordpress/CustomPostType/Item.php
- src/Wordpress/CustomPostType/Location.php
nähere Beschreibung siehe Ticket
> solves Bug / Plugin-Kompatibilität: All-in-one-Event-Plugin #675

- src/View/Item.php
- src/View/Location.php
- src/View/View.php
closing #1018 
Die Umsetzung mit dem geringsten technischen Aufwand.
> added order & orderby parameter to shortcodes #1018

- includes/Admin.php
- src/Wordpress/CustomPostType/Timeframe.php
Damit geht das mit relativ wenig Aufwand von unserer Seite, die entsprechende Person muss dann halt ein bisschen mehr programmieren. closing #1063
> filter hooks for timeframe defaults #1063

- src/Messages/Message.php
closing #1052 
Durch die Übergabe des $action Arguments kann geprüft werden bei welcher Art von Mail der Filter ausgelöst werden soll
> Anhänge in Buchungsbestätigung

- src/View/TimeframeExport.php
> changes default export value to ISO 8601

- src/Wordpress/CustomPostType/Map.php
Dummer Tippfehler.
closing #1118
> map: fixes location category pre-filtering

- readme.txt
> Updated version support

- src/Service/Scheduler.php
> added deprecated filter hooks to schedule for removing

- src/Helper/Wordpress.php
Nur autoformatting. @hansmorb Kannst du gerne squashen.
> Formatting

- src/Model/Timeframe.php
- src/Plugin.php
- src/Wordpress/CustomPostType/Timeframe.php
> Set booking days default value to 31 resolve #1236

- .github/workflows/php.yml
- composer.json
- composer.lock
- phpunit.xml.dist
- src/Helper/Helper.php
- src/Model/Booking.php
- src/Model/Calendar.php
- src/Model/Location.php
- src/Model/Timeframe.php
- src/Model/Week.php
- tests/Model/BookablePostTest.php
- tests/Model/BookingTest.php
- tests/Model/CalendarTest.php
- tests/Model/LocationTest.php
- tests/Model/TimeframeTest.php
- tests/Model/WeekTest.php
- tests/Wordpress/CustomPostTypeTest.php
* Testet Methoden im Booking-Model
* Fixed eine Änderung am Model aus Refactoring (#1141) => habe glaube ich eingeführt.
* Kleinere Änderungen am Model\TimeframeTest um alle Grenzfälle abzudecken
Einige Methoden im Model sind schwierig zu testen und passen (finde ich) auch nicht 100% ins Model:
* Im Model sind Methoden die HTML rendern 
* Im Model sind Methoden die Logik des Buchungsprozesses enthalten
Dadurch wird es schwieriger das Model Unit zu testen.
Beispiel:
* `bookingNotice` rendert HTML. Sollte wahrscheinlich eher in die View, aber möglicherweise ist es Einfacher das direkt über das Model Objekt aufzurufen?
* `assignBookableTimeframeFields` enthält Buchungs-Logik
Bin aktuell noch unschlüssig wo sie besser passen.
> Unit-Tests für Model Klassen

- src/Service/Cache.php
> added other shortcodes to warmup #1243

- src/Migration/Migration.php
- src/Model/Booking.php
- src/Model/Timeframe.php
- src/View/Calendar.php
- src/View/TimeframeExport.php
- src/Wordpress/CustomPostType/Booking.php
- src/Wordpress/CustomPostType/Timeframe.php
Kleine Änderungen ohne funktionale Auswirkungen
> Small refactoring

- Gruntfile.js
Fixes #586 via `compass:clean`
> Cleans css files to force minification

- src/Wordpress/CustomPostType/Booking.php
> fix 1279 fatal error

- .distignore
- .github/workflows/wordpress.yml
- .gitignore
- package-lock.json
- package.json
Mein Versuch die Deploy Action zu reparieren, ich habe sie auch mal von Tag auf deploy umbenannt. Bei mir hat das ganze lokal getestet mit act (https://github.com/nektos/act)  bis auf den letzten Schritt ganz gut geklappt. Die push action nach dem grunt task konnte ich auch nicht testen. Ich musste nur leider einige externe Actions hinzufügen um das ganze System aufzubauen. 
Ich habe auch npm ci statt npm, weil das soweit ich das richtig verstanden habe in automatisierten Umgebungen eher benutzt werden soll.
> Fix deploy action

- src/View/Item.php
Der Parameter ist noch nirgendwo dokumentiert aber wirft jetzt wenigstens keinen Fatal error mehr
closes #1070
> fixed shortcode #1070

- src/View/Calendar.php
- templates/shortcode-items_table.php
- templates/timeframe-calendar.php
> Fixed small HTML bugs in calendar table  #1364

- src/Model/Day.php
Vorher diskutiert hier https://github.com/wielebenwir/commonsbooking/pull/1371#issuecomment-1774092391
> Hilfreiche User und Developer Informationen dokumentiert

- tests/php/View/CalendarTest.php
> tests for #1393

- composer.json
- composer.lock
Updates recommended dependencies, some possible (api-related) and composer update and composer bump.
> Updates composer dependencies

- includes/Admin.php
Wurde genau wie die public.js Scripts in der Public.php implementiert
closes #1535
> Versionierung Admin Scripts

- templates/booking-single.php
> change string #1482

- .wp-env.json
- readme.txt
https://wordpress.org/news/category/releases/
> WP 6.5 Support

- src/API/BaseRoute.php
This fixes #1562 by using opis error formatter to write schema validation errors to error_log.
See: https://opis.io/json-schema/2.x/php-error-formatter.html
> API: Use formatter to add schema validation msgs to response

- assets/admin/js/src/restriction.js
> fix #1586 - only apply for cmb2

- src/Plugin.php
> add taxonomy columns #1523

- src/Migration/Migration.php
- src/Model/BookingCode.php
- src/Plugin.php
- src/Repository/BookingCodes.php
- tests/php/Repository/BookingCodesTest.php
Reverts wielebenwir/commonsbooking#1497
> Revert "Beständige Bookingcodes"

- src/Helper/NominatimGeoCodeService.php
> added check for curl #1442

- src/Service/Cache.php
Existiert auch im Branch release/2.9.4
closes #1613
> fix #1613 (multisite cache)

- .github/ISSUE_TEMPLATE/bug_report.md
Diese Versionen sind glaube ganz sinnvoll zum Nachstellen.
@hansmorb hast du noch Dinge zum Ändern, die du gerne drin hättest, ansonsten merge es einfach.
> Issue-Template: Add php and plugin version

- .phpcs.xml.dist
- Readme.md
- readme.txt
> Small docs and phpcs changes

- .wp-env.json
- readme.txt
> WP 6.7 Kompatibilität

- .github/workflows/e2e.yml
- .github/workflows/phpunit.yml
Uses the latest stable php version in the repository workflows.
> Use latest stable php version

- composer.json
- composer.lock
The IDE checks against the PHP version configured in the composer.json to set the PHP language level.
> Raise php minimum requirement to >=7.4

- .phpcs.xml.dist
As "requested" by @hansmorb here: https://github.com/wielebenwir/commonsbooking/pull/1693#discussion_r1888923120
Should be merged before: https://github.com/wielebenwir/commonsbooking/pull/1693
> Disable short array syntax sniff

- src/View/Calendar.php
- tests/php/View/CalendarTest.php
> fixes #1720 (calendar crash)

- .github/workflows/build-rc.yml
- .github/workflows/compile.yml
- .github/workflows/e2e.yml
- .github/workflows/phpstan.yml
- .github/workflows/phpunit.yml
- .github/workflows/release.yml
- .github/workflows/zip-pr.yml
> upgrade all workflows to ubuntu 24.04

- src/Wordpress/CustomPostType/Timeframe.php
- tests/php/Wordpress/CustomPostType/TimeframeTest.php
> fix cb_manager can create block for all items in instance (#1785)

- composer.json
- composer.lock
composer.json was missing php extensions that we are using in plugin code and test code.
> Add missing php extensions

- src/Model/Booking.php
- src/Model/Map.php
- src/Plugin.php
- src/Repository/BookablePost.php
- src/Repository/Item.php
- src/Repository/Location.php
- src/View/Calendar.php
- src/Wordpress/CustomPostType/CustomPostType.php
- src/Wordpress/CustomPostType/Item.php
- src/Wordpress/CustomPostType/Location.php
- src/Wordpress/CustomPostType/Timeframe.php
This factors out all occurences of `cb_*s_category` and uses the approriate `getTaxonomyName()` cpt method.
> CustomPostTypes: add generic way of taxonomy name getter

- phpstan-baseline.neon
- src/Model/Calendar.php
- src/Service/BookingCodes.php
- src/View/BookingCodes.php
Fixes phpstan issues from merge of dependabot #1833 
Should be merged before #1822
> Fix phpstan issues after update

- src/Wordpress/CustomPostType/Location.php
Fixes issue https://github.com/wielebenwir/commonsbooking/issues/1867
> Removed forward slash to fix link
