- src/Messages/AdminMessage.php
- src/Wordpress/Options/AdminOptions.php
@markus-mw Hab eine AdminMessage-Klasse hinzugefügt, die das erzeugen von Admin-Notices vereinfacht.
Schau mal drauf und wenn das so passt, dann bitte mergen und gerne die Klasse generell für alle Admin-Notices verwenden. 
Merci.
> added admin message class

- commonsbooking.php
Let Wordpress interpet the strtotime()-compatible string which avoids time-zone related conversion issues. See also #532.
> Fix date conversion issue

- src/API/GBFS/Discovery.php
- src/API/GBFS/SystemInformation.php
- src/Plugin.php
This completes the existing GBFS API to the bare minimum to be GBFS
compliant and thus consumable by GBFS clients.
See also issue #627.
> Add GBFS discovery and system information API

- templates/map-admin-page-template.php
War vorher ein Textarea feld, das ergibt aber bei einem so kleinen Button keinen Sinn
> Changed from textarea to text, better fit for purpose

- src/View/Booking.php
Über den Filter kann man anpassen, welche Informationen für jede Buchung ausgegeben werden. Zum Beispiel könnte man dem [content-Objekt](https://github.com/wielebenwir/commonsbooking/blob/df32ec744b76a3473fec05de706c44e28a447c47/src/View/Booking.php#L127) weitere Item-Felder hinzufügen, die dann automatisch im Frontend mit ausgegeben werden.
Dies erscheint einfacher zu sein, als das Shortcode-Template im Theme zu überschreiben, da die Buchungen über JS ausgegeben werden.
Resolves #936
> Add filter hook for shortcode cb_bookings

- src/Model/Booking.php
- src/View/View.php
- src/Wordpress/CustomPostType/Booking.php
Dieser MR enthält einige zusätzliche Checks, um #1091 zu fixen.
Anscheinend wurde das Problem in `src/Wordpress/CustomPostType/Booking.php` parallel schon gelöst. Daher hier nur noch eine Whitespace-Korrektur dazu.
> Bugfix für #1091

- src/Service/Cache.php
> fix: only prune cache when interface is pruneable

- assets/map/js/cb-map-shortcode.js
This fixes getBounds error when max_cluster_radius is set to 0px, by computing `center_position` from the average lat/lon of all markers.
This will resolve #733 
I tested it with my local setup, with 3 locations there is no problem (See issue discussion).
I don't know about performance issue when there are many more markers to display.
When you accept it I will remove the debug logs.
> CB_MAP: Allows no-clustering with max_cluster_radius == 0px

- includes/OptionsArray.php
- src/Model/Booking.php
This adds email signature to the options array (settings -> 'template')
This will resolve #75 
Question: 
Is there already an function to replace a string like `{{E-Mail-Signature}}` in the body?
For exampe, when sending emails I can do either:
* If `{{E-Mail-Signature}}` is already in the body, replace the string and do not append it's contents to the body.
* If the string is not already in the body, then it's contents will be appended to the body.
> Adds email signature

- src/Model/Timeframe.php
- src/Repository/Booking.php
- src/Wordpress/CustomPostType/Booking.php
This PR optimizes the handling of full-day timeframes and streamlines bookings a bit by (see #1114):
- removing array_filter checks that are always true
- spezifying the return type of getByTimerange() more precisely
> #1114 Optimize full-day handling & refactoring

- src/Helper/Helper.php
- templates/timeframe-withitem.php
- templates/timeframe-withlocation.php
- tests/Helper/HelperTest.php
When two or more timeframes overlap, they are now merged into one bookable timeframe when displaying them to the user.
This resolves #1020
> TimeFrame Helper: Merge display of overlapping timeframes

- Readme.md
- readme.txt
Die beiden größten Wordpress-Plugins für Kalenderbuchungen enthalten keine Standorte.
Andere Buchungssysteme (auch außerhalb von WP) entweder auch nicht oder einfach nur keine Karte.
Demanch würde ich die Karte als wichtiges einzigartiges Feature hervorheben.
> Standortkarten Shortcode ist ein unique feature

- Readme.md
- composer.json
- readme.txt
So our plugin can be found more easily.
Removes version because it's not necessary, commonsbooking.php is parsed by Wordpress-Plugin-Backend.
@chriwen @hansmorb vielleicht noch mit diesem Release?
> Update readme.txt tags to be more descriptive

- includes/OptionsArray.php
- src/Service/Cache.php
Closing #1166 
Gibt bei Hostern, die keinen Zugriff auf den /tmp/ Ordner gewähren, die Möglichkeit den Cache in einem anderen Ordner zu speichern (zum Beispiel in wp-content/cache)
> added path option for cache #1166

- src/Model/Calendar.php
- src/Model/Day.php
- src/Model/Week.php
- src/Repository/BookablePost.php
- src/Repository/Booking.php
- src/Repository/BookingCodes.php
- src/Repository/PostRepository.php
- src/Repository/Restriction.php
- src/Repository/Timeframe.php
- src/View/Booking.php
- src/View/Calendar.php
- src/View/Item.php
- src/View/Location.php
closes #1302 
Ich habe das gemacht, weil die Fehlermeldung in der verlinkten issue sehr stark darauf schließen lässt, dass sich der Cache Wert zwischen den Abfragen verändert hat. Sowieso wäre es ja vielleicht gut nicht zweimal auf das gleiche Cache Element zuzugreifen wenn es nicht nötig ist, oder? Vor allem weil die meisten ja einen langsamen filesystem Cache nutzen.
> #1302 moved cacheItem to variable

- src/Helper/Wordpress.php
- src/Repository/Restriction.php
- tests/Helper/WordpressTest.php
- tests/Repository/RestrictionTest.php
- tests/Repository/TimeframeTest.php
Der Cache erwartet anscheined stringvals, da aber die getRelatedPostIds schon stringval benutzt, habe ich mir das hier gespart.
So kann ich das auch einfacher Unit testen.
Ich bewahre hier mehr den Status quo, die Tests sind an den aktuellen Ergebnissen der Funktion orientiert. Ganz genau bin ich in der Funktionsweise noch nicht durchgestiegen.
> added unit tests for cache invalidation

- src/Wordpress/CustomPostType/CustomPostType.php
Schließt die #1309 . Leider wird dabei die Sortierung kaputtgemacht, diese hätte aber wahrscheinlich sowieso überarbeitet werden müssen, weil die entsprechende Variable mit dem Meta-Key seit dieser WP Version auch nicht mehr übergeben wird. Nach dem mergen bitte eine entsprechende issue erstellen.
> Behebt Fatal Error im Admin Backend

- .github/workflows/wordpress.yml
So it doesn't get triggered accidentally.
> Trigger release action only on semantic versions

- assets/global/js/vendor.js
- package-lock.json
- package.json
Das war ein Grunt Package (grunt-contrib-nodeunit) von dem ich jetzt einfach die nächste major Version genommen habe. Grunt lief bei mir (Node 20) ohne Probleme durch. Mir ist auch aufgefallen, dass es jetzt anscheinend die --legacy-peer-deps Flag nicht mehr braucht.
> fixed packages with vulnerable dependencies

- src/View/Item.php
- src/View/Location.php
- tests/View/ViewTest.php
Entfernt überflüssiges Sortieren `getShortcodeData` gibt bereits nach `startdate` sortierte Ranges raus.
> Remove unnecessary sorting

- .github/workflows/build-rc.yml
Damit können wir bei einem Push auf einen release branch uns sofort eine Plugin zip generieren lassen, die war dann direkt zum Testen nutzen können bevor wir den release auf wordpress.org veröffentlichen.
> add action to build zip on release branch

- assets/map/js/cb-map-locationview.js
- assets/map/js/cb-map-positioning.js
This increases the timeout of the callback to Map-'load'-event, which eventually invalidates the size of the map to trigger a repaint.
> Fixes missing tiles and positiong on map

- src/Wordpress/CustomPostType/Booking.php
Der kleine quirk ist mir so nebenbei aufgefallen, warum entfernen wir den Author mit einer eigenen Funktion, wenn er auch einfach aus dem 'supports' array entfernt werden kann?
> booking author no longer removed by function but support removed

- src/API/AvailabilityRoute.php
- src/API/GBFS/StationStatus.php
- src/Model/Calendar.php
- src/Model/Day.php
- src/Model/Timeframe.php
- src/Repository/BookablePost.php
- src/View/Calendar.php
- tests/php/API/GBFS/StationStatusTest.php
- tests/php/Model/BookingTest.php
- tests/php/Model/CalendarTest.php
- tests/php/Model/DayTest.php
- tests/php/View/CalendarTest.php
- tests/php/Wordpress/CustomPostTypeTest.php
Ziel dieses Fix ist es, dass nur Artikel, die tatsächlich gerade an der Station direkt ausleihbar wären auch als solchen angezeigt werden, weil die GBFS Spezifikationen das so fordern. 
Vor diesem Patch war es so, dass einfach alle Artikel an der Station angezeigt wurden. Unabhängig von Verfügbarkeit: Gebucht / Urlaub / Reperatur.
Zu diesem Zweck habe ich die API/AvailabilityRoute refactored und das Berechnen der verfügbaren Slots in die Model/Calendar Klasse ausgelagert. So kann diese Methode auch zum Berechnen der verfügbaren Artikel  für die GBFS API Route verwendet werden. Dabei werden immer nur die Daten für den heutigen Tag genommen, weil GBFS sich nicht für zukünftige Verfügbarkeiten interessiert.
Diese Methode hat vorher auch nicht das booking-offset mit einberechnet, dh., dass …
> Fix:  GBFS: Availability wird nicht berücksichtigt #1332 

- src/Plugin.php
- src/Service/Upgrade.php
- tests/php/Service/UpgradeTest.php
- tests/php/Wordpress/CustomPostTypeTest.php
Das war ursprünglich Teil von #1306 , wurde aber zum einfacheren Review ausgegliedert.
Warum:
-Die Plugin Klasse wurde mit den ganzen Migrationen langsam etwas unübersichtlich
-Jetzt haben wir eine Möglichkeit Upgrade Tasks nur 1x (nämlich bei dem Upgrade über die Version) laufen zu lassen. So wird zum Beispiel nicht ständig das Farbschema bei jedem Upgrade zurückgesetzt
> Upgrade Methoden umbauen

- src/Helper/GeoCodeService.php
- src/Helper/GeoCoderServiceProxy.php
- src/Helper/GeoHelper.php
- src/Helper/NominatimGeoCodeService.php
- tests/php/API/CB_REST_UnitTestCase.php
- tests/php/BaseTestCase.php
- tests/php/Helper/GeoHelperTest.php
- tests/php/Wordpress/CustomPostTypeTest.php
Das funktioniert. Ich war mir unsicher ob es nicht doch schöner (wartbarer/lesbarer) ist, das direkt über das StatefulGeocoder oder Provider interface/class zu lösen. Habe es jetzt erstmal so gelassen, da es eine so kleine API ist und so wenig Funktionatlität betrifft, die wir nutzen, sodass wir die nicht besonders konfigurierbar hervorheben müssen.
Siehe: https://github.com/wielebenwir/commonsbooking/discussions/1411
> Unit-Tests: Mock calls to nominatim geocoding service

- .github/actions/build-plugin/action.yml
- .github/workflows/compile.yml
Da wir jetzt node-sass nutzen müssen wir compass nicht mehr installieren.
> remove ruby from actions

- src/Messages/BookingMessage.php
- src/Messages/BookingReminderMessage.php
- src/Messages/Message.php
- src/Messages/RestrictionMessage.php
- src/Settings/Settings.php
- tests/php/Settings/SettingsTest.php
Hallo zusammen,
wenn ein Absender-Name mit Sonderzeichen gewählt ist, in meinem Fall so:
Dann werden beim Senden die Sonderzeichen in HTML Entities in Settings::getOption mit commonsbooking_sanitizeHTML() umgewandelt. Leider sind HTML Entities wie &amp; in E-Mail-Headers nicht zulässig. Das Ergebnis:
Ein "legales" Zeichen wie & soll besser einfach belassen werden. Mit diesem PR habe ich 
1. den Code in getOption vereinfacht. Die Funktion Settings::flattenArray tat gar nicht was der Name glauben lässt, sondern ließ die Array-Struktur exakt gleich bleiben. flattenArray ließ commonsbooking_sanitizeHTML auf jedes Element laufen. Das kann man besser mit der Wordpress-Funktion map_deep machen. Außerdem wurde unnötig viel Rechenleistung beansprucht, denn die gesamte Optionsarray wurde bisher mit …
> Fix für E-Mail-Absender-Namen mit Sonderzeichen wie "Frieda & Friedrich"

- src/API/GBFS/BaseRoute.php
- src/API/GBFS/StationStatus.php
Fixes the "easy" part of the issue, the wrong last_updated / last_reported GBFS field. 
The other part is the wrong status calculation. Here, I'm not sure in which timezone booking dates are supposed to be saved in the DB.
> #1388: fix last_updated / last_reported

- src/API/BaseRoute.php
- src/API/ItemsRoute.php
Zum Testen:
Mit bin/build-zip.sh eine Plugin ZIP erstellen und schauen, ob die API Routen mit WP_DEBUG aktiviert noch funktionieren. Wurde noch nicht manuell getestet.
closes #1408
> Bugfix/issue 1408 (API Validation)

- src/Repository/BookingCodes.php
- tests/php/Repository/BookingCodesTest.php
Ich habe vor, wenig größere Änderungen bei den BookingCodes vorzuschlagen. In der Vorbereitung dafür sind mir kleinere Fehler und unvollständige/inkonsistente Doku aufgefallen, die mit dem eigentlichen Vorhaben nicht direkt zu tun haben. Nach dem Modell Salamitaktik ist es vielleicht vorteilhaft, kleine Schritte zu gehen, die ich als unumstritten einschätzen würde. Solche Änderungen schlage ich mit diesem PR vor.
> BookingCodes: Kleine Fixes und Verbesserung der Code-Doku

- includes/Users.php
- src/Plugin.php
- src/Repository/UserRepository.php
Ich habe mich dagegen entschieden den von den Nutzenden erstellten Administratoren (bzw cb-admins) alle Berechtigungen auf die Instanz zu geben.
1. Der Hook wird nur bei einem Update ausgeführt, demnach sparen wir uns etwas Trickserei
2. Die Nutzenden sollen möglichst viel Kontrolle über die Fähigkeiten dieses Custom CB-Admin haben, wenn bei jedem Update die Berechtigungen zurückgesetzt werden ist das nicht so knorke. 
Und das Zuweisen neuer Berechtigungen ist mit einem Plugin wie User Role Editor ja auch keine große Sache.
closes #1463
> Bugfix/issue 1463 (commonsbooking_admin_roles Hook verwirrend)

- src/Service/Holiday.php
- src/Wordpress/CustomPostType/Restriction.php
Habe festgestellt, dass "Status" im Kontext von Restrictions wesentlich mehr Sinn ergibt als "State". Habe trotzdem Kontext für "State" hinzugefügt da "State" sehr viele verschiedene Bedeutungen haben kann wie z.B. Zustand, Verfassung, etc.
closes #1489
> fix #1489 (Status / State)

- includes/Users.php
- src/Plugin.php
- src/Repository/UserRepository.php
Nur minimale Änderung die vergessen wurde um das Feature konsequent durchzuziehen. Jetzt kann der Hook commonsbooking_manager_roles wie in der Dokumentation beschrieben verwendet werden. Wenn für den Custom Manager die Berechtigungen manuell genau wie die für den CB-Manager gesetzt werden, dann kann diese Rolle genau so viel wie ein CB-Manager.
closes #1461
> Bugfix/issue 1461 (Metaboxen Custom CB-Manager)

- assets/map/js/cb-map-positioning.js
- src/Plugin.php
- src/View/Map.php
- tests/cypress/e2e/cpt-creation.cy.js
- tests/cypress/e2e/cpt-frontend-pages.cy.js
- tests/cypress/wordpress-files/e2e-override.json
In den Feldern für die Erstellung / des Bearbeitens eines Standorts wird automatisch die Karte für die Adresse abgerufen (wenn keine Latitude oder Longitude übergeben wurde). Vorher hat das auch für neue Posts funktioniert, weil die API bei leerer Adresse einfach eine leere Antwort gegeben hat um dann die Default Koordinaten einzustellen. Anscheinend haben die bei OSM ihre API geändert, jetzt schlägt der JSON Befehl fehl, wenn keine Addresse definiert wurde (wie zum Beispiel bei einem neuen Artikel). Das alte JS hat mit einer leeren Antwort gerechnet und nicht den "fail" case in Betracht gezogen, das wurde jetzt nachgeholt.
Ich vermute, dass dieser Fehler schon seit einer ganzen Weile existiert, er ist mir über ein altes Tutorial Video von vor einem Jahr aufgefallen.
Zu dem neuen …
> Bugfix/issue 1428 (Positionierungskarte)

- src/View/TimeframeExport.php
- tests/php/View/TimeframeExportTest.php
Adds the fix and additional tests to validate the fix.                                                                   
The commit 8d98c00317e219dc0185adab8ec1e9f88ebba949 introduced this bug.                                                 
It had the purpose to allow timesframes (for holidays) to be "mutli-selected" with more than one location or item.       
This fixes the export, but won't include custom-fields of location- and item-posts, related to holiday-timeframes in the 
export file.
> Fixes errors in TimeframeExport (Issue #1532)

- src/API/BaseRoute.php
This needs to load a local file path and no remote path. Reverts commit 751b26a3902cf67f1690775eb9dd95eac32c991f
> API: Fix #1531

- Gruntfile.js
- src/API/AvailabilityRoute.php
- src/API/BaseRoute.php
- src/API/ItemsRoute.php
- src/API/LocationsRoute.php
- src/API/OwnersRoute.php
- src/API/ProjectsRoute.php
This is a fix for #1466; it moves common-api schema files at grunt-build time to the assets folder and changes the relevant paths.
Fixes #1466
> API: Adds commons-api schema files as assets

- src/API/BaseRoute.php
The Opis dependency was updated in 4c99c15e61fdeaeee23ae8eb9f738709e2cc10a1, but because of #1531 the code was unreachable and the bug wouldn't occur. After patching #1531, this code can be reached and a fix is necessary, because the API of OPIS JSON Parser got a majore refactoring.
See migration guide: https://opis.io/json-schema/2.x/php-validator.html#data-validation
Though it fixes partially #1466, the issue with possible missing schema files in production which should be moved from `node_modules` into the `commosnbooking` plugin dir prevails (and is fixed in #1547).
> Fix usage of opis 2.0 interface

- src/View/Calendar.php
Fixes #1567
Won't support meta keys at the moment.
> Shortcodes: cb_items_table supports order/orderby now

- assets/public/css/public.css
- assets/public/sass/partials/_map.scss
Ermöglicht den Text mit dem post_excerpt im Popup anzuzeigen. Das war auch ursprünglich aktiviert im CB1 Karten Plugin:
Die Funktion existierte also schon, wurde aber anscheinend per CSS ausgeschaltet. Gibt es dafür einen triftigen Grund? 
Das wurde damals in commit 0e90d291a6d952b269edbe7bf9d43ad4a6a13c9b deaktiviert und dann nie wieder eingeführt. 
closes #1300
> show excerpt element in map #1300

- src/Migration/Migration.php
- src/Model/BookingCode.php
- src/Plugin.php
- src/Repository/BookingCodes.php
- tests/php/Repository/BookingCodesTest.php
Mit diesem PR 
- werden generierte Codes nie gelöscht (sind Listen ausgedruckt, behalten sie ihre Gültigkeit), sondern bleiben ewig gespeichert, wenn einmal für ein Lastenrad erstellt.
- haben die Codes keinen Timeframe- oder Location-Bezug mehr (ändert ein Lastenrad z.B. aufgrund von Urlaub die Verleihstation sollen ausgedruckte Listen sowie bereits übermittelte Codes in Buchungsbestätigungen ihre Gültigkeit behalten)
- wird Bug #1477 behoben
- wird Feature #1498 umgesetzt
- wird der Code vereinfacht:
- BookingCodes.php: 430 -> 359 Zeilen (-71)
- BookingCode.php: 176 -> 79 Zeilen (-97)
> Beständige Bookingcodes

- src/Wordpress/CustomPostType/Booking.php
- tests/php/Wordpress/CustomPostType/BookingTest.php
Falls ein Buchungsrequest mit Referenz auf eine Post_ID abgsetzt wird (im Normalfall bedeutet das die Bestätigung einer unbestätigten Buchung oder das Stornieren einer unbestätigten Buchung) wird nochmal zusätzlich geprüft, ob dieser Post überhaupt existiert.
closes #1584
> fix #1584 (unerwartetes Verhalten durch unconfirmed booking cleanup)

- tests/php/Repository/TimeframeTest.php
- tests/php/Service/BookingRuleAppliedTest.php
Mit Bezug auf #1605 ist das Ziel dieser PR, die u.g. Warnungen loszuwerden. PHP erlaubt es (bald) nicht mehr, properties dynamisch zu deklarieren. Die Lösung ist also, die betroffenen properties in der class-Definition zu deklarieren.
> PHP Deprecated:  Creation of dynamic property CommonsBooking\Tests\Repository\TimeframeTest::$timeframeId is deprecated in /home/runner/work/commonsbooking/commonsbooking/tests/php/Repository/TimeframeTest.php on line 485
> PHP Deprecated:  Creation of dynamic property CommonsBooking\Tests\Repository\TimeframeTest::$otherItemId is deprecated in /home/runner/work/commonsbooking/commonsbooking/tests/php/Repository/TimeframeTest.php on line 41
> PHP Deprecated:  Creation of dynamic property CommonsBooking\Tests\Repository\TimeframeTest::$otherLocationId is …
> Warnung loswerden: Creation of dynamic property ... is deprecated

- src/Map/SearchShortcode.php
Mit Bezug auf #1605 ist das Ziel dieser PR, u.g. Warningen unter WP latest PHP 8.2. loszuwerden. Statt ${var} habe ich mit der PR vorgeschlagen, einfach $var zu schreiben in Strings mit doppelten Anführungszeichen. Man könnte auch die moderne Variante {$var} nutzen, aber die ist nicht einfacher zu lesen.
> PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /home/runner/work/commonsbooking/commonsbooking/src/Map/SearchShortcode.php on line 26
> PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /home/runner/work/commonsbooking/commonsbooking/src/Map/SearchShortcode.php on line 28
> PHP Deprecated:  Using ${var} in strings is deprecated, use {$var} instead in /home/runner/work/commonsbooking/commonsbooking/src/Map/SearchShortcode.php on …
> Change deprecated way of string interpolation

- tests/php/View/BookingTest_AJAX_Test.php
Mit Bezug auf #1605 ist das Ziel dieser PR, die u.g. Warnung loszuwerden. Sie kam zu stande, weil die Tests in BookingTest_AJAX_Test die DB-Tabelle wptests_cb_bookingcodes erstellen, aber nicht wieder löschen. Die Lösung ist, die Tabelle in tearDown() ordentlich zu löschen.
> WordPress database error Table 'wptests_cb_bookingcodes' already exists for query CREATE TABLE wptests_cb_bookingcodes (
>             date date DEFAULT '0000-00-00' NOT NULL,
>             timeframe bigint(20) unsigned NOT NULL,
>             location bigint(20) unsigned NOT NULL,
>             item bigint(20) unsigned NOT NULL,
>             code varchar(100) NOT NULL,
>             PRIMARY KEY (date, timeframe, location, item, code) 
>         ) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci; made by …
> BookingTest_AJAX_Test: proper cleanup of created database table

- src/Messages/BookingCodesMessage.php
- tests/php/Service/BookingCodesTest.php
- tests/php/View/BookingCodesTest.php
Mit Bezug auf #1605 , das Ziel dieser PR ist, diese Fehlermeldungen in phpunit unter "WP latest on PHP 8.2" loszuwerden. Diese Sequenz trat insgesamt zwei mal auf und wurden durch die Test-Funktionen Service::BookingCodesTest::testSendBookingCodesMessage() und View::BookingCodesTest::testSendBookingCodesMessage() ausgelöst. Siehe Commitbeschreibung für Details.
```
PHP Deprecated:  preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated in /tmp/wordpress/wp-includes/PHPMailer/PHPMailer.php on line 1880
PHP Deprecated:  is_file(): Passing null to parameter #1 ($filename) of type string is deprecated in /tmp/wordpress/wp-includes/PHPMailer/PHPMailer.php on line 1895
PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in …
```
> fix BookingCodesMessage:sendMessage() wrong $attachment for prepareMail

- tests/php/Wordpress/CustomPostType/TimeframeTest.php
Mit Bezug auf #1605 ist das Ziel dieser PR die u.g. Fehlermeldungen (WP latest PHP 8.2) loszuwerden. Die Warnungen wurden vom Test testRemoveIrrelevantPostmeta() ausgelöst, weil update_post_meta() fehlerhaft mit einem Objekt statt mit einer Post-ID aufgerufen wurde. Anmerkung: Der Test kann vorher nicht funktioniert haben, nach der PR ist er weiterhin erfolgreich. 
> PHP Deprecated:  Creation of dynamic property CommonsBooking\Model\Timeframe::$ID is deprecated in /tmp/wordpress/wp-includes/post.php on line 2808
> PHP Deprecated:  Creation of dynamic property CommonsBooking\Model\Timeframe::$filter is deprecated in /tmp/wordpress/wp-includes/post.php on line 2813
> fix testRemoveIrrelevantPostmeta

- src/Repository/BookingCodes.php
- tests/php/Repository/BookingCodesRandomnessTest.php
- tests/php/Repository/BookingCodesTest.php
Booking codes were generated deterministically with an obvious pattern. Now generate with the recommended and cryptographically secure random_int() of PHP.
> Generate random booking codes (fix issue-1110)

- .wp-env.json
- commonsbooking.php
- readme.txt
> WP 6.6 Kompatibilität

- src/Repository/BookingCodes.php
- tests/php/Repository/BookingCodesTest.php
- tests/php/View/BookingTest_AJAX_Test.php
With this feature, no codes are generated for past days anymore. A test case was added and other unit tests were fixed because they actually relied on generation of codes for the past.
This implements #1602
> implement feature issue-1602: no code generation for past

- src/View/Booking.php
*Was*
Die Buchungsliste zeigt mit der Initialkonfiguration nur Buchungen ab dem heutigen Tag an. Wenn vergangene Buchungen angezeigt werden sollen, muss über den Filter das Startdatum in die Vergangenheit gesetzt werden. Eben dieser Filter wird aber nicht angezeigt, wenn keine Buchungen vorhanden sind. Deshalb sorgt dieser PR dafür, dass bei nicht gesetztem Startdatum und keinen Buchungen in der Zukunft sukzessive die letzten drei Jahre durchsucht werden um Nutzenden wenigstens eine Buchung anzeigen zu können. Von da aus können Nutzende dann mit dem ihnen nun angezeigten Filter auch weiter in der Vergangenheit ihre Buchungen sehen. 
* Mögliche Probleme * 
Wenn Nutzende keine Buchungen in den letzten drei Jahren getätigt haben wird ihnen die Buchungsliste wieder nicht angezeigt. 
* …
> fix #1229 (Vergangene Buchungen in Buchungsübersicht)

- src/Wordpress/CustomPostType/Restriction.php
Weil der Bugfix #1273 nicht so trivial ist deaktiviert dieser PR vorerst die Funktion "Alle" bei der Zuweisung von Einschränkungen zuzuweisen. 
Auf Wunsch von der Flotte, TODO für uns ist besprechen, ob wir das auch allgemein releasen wollen oder ob wir warten sollen bis wir den Bugfix für #1273 raushaben.
> Einschränkungen für ALLE deaktivieren

- src/Map/BaseShortcode.php
- src/Map/MapShortcode.php
- src/Map/SearchShortcode.php
- src/Plugin.php
- src/Service/Cache.php
- src/Wordpress/CustomPostType/Map.php
Fixes #1636 
TODOs:
@hansmorb Der Aktuelle Stand, mitigiert bereits das Verhalten im Issue: Es werden alle Shortcodes ausgeführt. Aber die auftretende Exception ist noch nicht behoben.
> Cache: Warmup does not exit if an shortcode call has an exception

- src/View/Calendar.php
Fixes a warning about undefined variable $firstbookableday in commonsbooking/src/View/Calendar.php (Line: 399)
```
Error code: E_WARNING
[Message]:
Undefined variable $firstbookableday
```
@hansmorb I don't really at the moment if null is a problem here for the JS client code, but it was null for calendars with no timeframes (see the if and the count in Line 363/364) in the past anyways, so I figured it should work this way.
> Calendar: Fix warning about Undefined variable $firstbookableday

- composer.json
- composer.lock
At the moment we already use phpunit 9 for running the tests anyway (see github workflow) and depend in our testsutie on functions like `assertMatchesRegularExpression`, which are available since phpunit v9. 
So this updates it (and the dependencies) in our composer dev section.
> composer: upgrades phpunit from 8 to 9

- .github/dependabot.yml
@hansmorb So we track updated dev-dependencies via auotmatic pull requests.
> Enable dev-dependencies for dependabot

- templates/map-admin-page-template.php
Der Code für die unterschiedlichen Map style Feature der Karten ist leider etwas über verschiedene PHP/JS Files verteilt.
1. Die Anpassungen im Template habe ich hier im Pull commitet.
2. Die URLs der Styles sind hier im JS hinterlegt: https://github.com/wielebenwir/commonsbooking/blob/22ef5c84c210387240efe1f563672f4980f7efac/assets/map/js/cb-map-shortcode.js#L11
3. Die Validierung der int codes hier:
https://github.com/wielebenwir/commonsbooking/blob/22ef5c84c210387240efe1f563672f4980f7efac/src/Map/MapAdmin.php#L216
(2) und (3) habe ich vorerst mal drin gelassen, da aktuell glaube nicht klar ist ob die wieder rein kommen oder? Aber ich hätte auch nichts dagegen alles sauber umzusetzen. Was denkst du @hansmorb ?
Aber ansonsten wären die Code-Stellen (1), (2) und (3) auch relevant für die …
> Disable map styles that seem inactive

- assets/admin/sass/admin.scss
- assets/admin/sass/lib/_jquery-ui.scss
- assets/admin/sass/partials/_dashboard.scss
- assets/global/sass/global.scss
- assets/global/sass/partials/_extends.scss
- assets/public/sass/partials/_bookings.scss
- assets/public/sass/partials/_calendar.scss
- assets/public/sass/partials/_forms.scss
- assets/public/sass/partials/_layouts.scss
- assets/public/sass/partials/_lists.scss
- assets/public/sass/partials/_map.scss
- assets/public/sass/partials/_notice.scss
- assets/public/sass/partials/_shortcodeItemsTable.scss
- assets/public/sass/partials/_single.scss
- assets/public/sass/public.scss
- package-lock.json
- package.json
@hansmorb 
Ich habe den Sass Code soweit angepasst das Warnings/Errors nicht mehr auftauchen, also der `npm run dist` jetzt erfolgreich durchläuft. Der erzeugte CSS Code unterscheidet sich aber. Ob das ein Problem ist weiß ich noch nicht, da ich das Aussehen des Plugins mit dem neuen CSS Code noch nicht getetst habe.
Ich habe die Änderungen in der Commit Nachricht beschrieben. Der Branch geht nicht vom Master ab sondern vom Dependabot Pull.
Es tauchen jetzt nur die Deprecations für die Verwendung der Legacy-JS API im [`grunt-dart-sass`](https://www.npmjs.com/package/grunt-dart-sass) Plugin auf. Ich glaube wir können auch das `grunt-sass` Plugin für `dart-sass` nutzen. Die Konfiguration im `Gruntfile` sieht auf den ersten Blick ähnlich aus. Da bin ich aber noch nicht im Detail drin. Die …
> Migration Sass 1.80

- assets/admin/css/admin.css
- assets/admin/sass/partials/_dashboard.scss
- assets/public/css/public.css
- assets/public/sass/partials/_calendar.scss
- assets/public/sass/partials/_forms.scss
- assets/public/sass/partials/_lists.scss
- assets/public/sass/partials/_map.scss
- assets/public/sass/partials/_notice.scss
- assets/public/sass/partials/_shortcodeItemsTable.scss
- assets/public/sass/partials/_single.scss
Fixes #1712 
The migration of sass in commit 37059c40da90fea0e03ea1170b3d073a918e0a47 (PR https://github.com/wielebenwir/commonsbooking/pull/1671) introduced several occurences of the optional keyword. This caused the styles being uncompletly generated, because the class-names before the keyword did not get resolved properly and thus CSS not being generated. This was because I did not understood the problem enough. This commit introduces explicit commits to the partials files that define the class-names.
> Fix #1712 with explicit sass imports via use

- src/Service/Scheduler.php
- tests/php/Service/SchedulerTest.php
This fixes #1605 (last open problem): The php test with race condition. 
See discussion in #1605.
> Fix #1605 last php unit test

- assets/admin/js/admin.js
- assets/admin/js/src/booking.js
This prevents malformed AJAX calls and avoids weird errors in the php log.
Instead, an "early return" and a javascript console warning are implemented. The solution is not 100% satisfactory. An ultimate solution would make sure that only relevant admin.js code is enqueued for a certain backend admin page and that would make this early return unnecessary.
We can discuss a better solution. I would be open to implement that as well.
> Workaround for #1724: Prevent admin.js from executing on invalid end pages

- src/Wordpress/CustomPostType/Booking.php
> fix #1688 (error in booking list when user deleted)

- includes/Users.php
- src/Plugin.php
- tests/php/PluginTest.php
Closes #1710 
Before, it unnecessarily initialized all CustomPostType classes, even when static access was sufficient.
Now uses static access on $postType variable
* Refactors methods to use class-string based lists instead of objects of custom post types.
> Plugin: Fix wp translation access

- includes/Admin.php
- includes/Template.php
- includes/TemplateParser.php
- includes/Users.php
- src/CB/CB.php
- src/Messages/BookingCodesMessage.php
- src/Messages/LocationBookingReminderMessage.php
- src/Messages/Message.php
- src/Model/Timeframe.php
- src/Repository/Restriction.php
- src/Repository/UserRepository.php
- src/Service/BookingRule.php
- src/View/Booking.php
- src/View/BookingCodes.php
- src/Wordpress/CustomPostType/CustomPostType.php
- src/Wordpress/Widget/UserWidget.php
Since we now can support [checking the phpdocs for `apply_filters`.](https://github.com/szepeviktor/phpstan-wordpress?tab=readme-ov-file#usage-of-an-apply_filters-docblock).
This pull requests aims to add phpdoc for all filters provided by the commonsbooking plugin.
So we can benefit from statically type checking their interfaces.
These filters are missing phpdoc at the moment. And there are some TODOs left.
```
./includes/Users.php:41020:	return apply_filters( 'commonsbooking_isCurrentUserAdmin', commonsbooking_isUserAdmin( $user ) );
./includes/Users.php:41051:	return apply_filters( 'commonsbooking_isCurrentUserCBManager', in_array( Plugin::$CB_MANAGER_ID, $user->roles ), $user );
./includes/Users.php:41058:	return apply_filters( 'commonsbooking_isCurrentUserSubscriber', in_array( …
```
> Documents commonsbooking filter hooks

- Readme.md
- readme.txt
Für die Übersichtlichkeit, da ja ziemlich viele Issues keine Bugs sind.
> Link to bug-labeled issues only

- .git-blame-ignore-revs
- .github/workflows/phpcbf-check.yml
- TECHNICAL.md
- src/Map/BaseShortcode.php
- src/Map/MapFilter.php
- src/Messages/Message.php
- src/Model/Timeframe.php
- src/Service/MassOperations.php
- src/View/Booking.php
- tests/php/Wordpress/CustomPostType/TimeframeTest.php
After running phpcbf on our codebase (#1730), this adds an automatic check, if we have any code format violations in future prs and suggests running phpcbf by the user.
Additionally I think it would be more comfortable for contributors to have an pre-commit hook, that checks if phpcbf should be run.
TODO
> Add phpcbf check workflow

- includes/Users.php
- phpstan.neon
- src/API/GBFS/StationInformation.php
- src/API/GBFS/StationStatus.php
- src/API/ItemsRoute.php
- src/API/LocationsRoute.php
- src/API/OwnersRoute.php
- src/Map/MapData.php
- src/Migration/Migration.php
- src/Model/Booking.php
- src/Model/CustomPost.php
- src/Model/Timeframe.php
- src/Repository/Booking.php
- src/Repository/UserRepository.php
- src/Service/BookingCodes.php
- src/Service/Cache.php
- src/Service/Scheduler.php
- src/Settings/Settings.php
- src/View/Booking.php
- src/View/Dashboard.php
- src/View/View.php
- src/Wordpress/CustomPostType/CustomPostType.php
- src/Wordpress/CustomPostType/Timeframe.php
- tests/php/API/GBFS/StationStatusTest.php
Successor of #1735. 
TODO
Goals of this PR (Copied from discussions of previous PRs):
* Use phpdoc `@params` or `@return` annotations where appropriate for type checks at (ci) build time
* Use [php type declarations](https://www.php.net/manual/en/language.types.declarations.php) where appropriate, for runtime checking (php language level 7.4)
For phpstan: Apart from general static type checking, my personal goal would be to reach at least [rule level 8](https://phpstan.org/user-guide/rule-levels), to check nullable types.
> Increase phpstan level 3

- assets/admin/js/src/export.js
This fixes the visibilty of the doneSpan (success message) and failedSpan (error message) on consecutive timeframe exports, by properly initializing them "on-click".
Before the (error or success) message of a previous export would still be visible after the next (error or success) run.
> TimeframeExport: hide previous success/error messages on consecutive export runs

- assets/public/js/src/litepicker.js
- src/View/Item.php
- templates/timeframe-calendar.php
Uses globalCalendarData from View/Item.php to instantiate litepicker with translated Strings from pot source, instead of static german labels.
Found this by accident, but I'm unsure if it's a problem or was a problem?
> Uses translated strings in LitePicker instantiation, instead of static german labels

- src/Model/Booking.php
- tests/php/Model/BookingTest.php
- tests/php/Wordpress/CustomPostTypeTest.php
When we receive the confirmation email for a booking, the return date shows the time of the booking instead of the time of the actual return date.
In the screenshot below: 11:55 should be 19:00.
This PR fixes it for us. I don't know if there was a specific reason for why it was implemented differently.
> Fix for wrong start time of return date

- src/Wordpress/Options/AdminOptions.php
When saving 0 to a value, the field is treated as empty. Therefore, if the default is 0, we will not save it to the field in case it is undefined.
closes #1416
> fix #1416 (empty default values saved)

- src/Service/TimeframeExport.php
- tests/php/Service/TimeframeExport_AJAX_Test.php
This PR changes the TimeframeExport to use a transient instead of pushing the list of relevant timeframes around between AJAX requests. This fixes the limit imposed by `max_input_vars`. Thx to @danielappelt for pointing that out.
closes #1793
> Fix timeframe export excluding bookings

- src/Model/Timeframe.php
- tests/php/Model/DayTest.php
fixed through updating getRepetition to always return 'norep' when it is not defined. repetition is usually not defined for bookings. Therefore we should return norep in those cases.
closes #1900
> fix #1900 (overbooking not counted)
